services:
  - type: web
    name: django-backend
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
databases:
  - name: mydb
    plan: free